# Generated by Django 6.0.6 on 2026-06-27 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0002_block'),
    ]

    operations = [
        migrations.AddField(
            model_name='field',
            name='acres',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='field',
            name='crop_type',
            field=models.CharField(blank=True, default='Rice', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='field',
            name='work_type',
            field=models.CharField(blank=True, default='Ploughing', max_length=50, null=True),
        ),
    ]
