# Generated by Django 6.0.6 on 2026-06-25 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='designation',
            name='name',
            field=models.CharField(choices=[('superuser', 'Superuser'), ('admin', 'admin'), ('vc', 'vc'), ('supervisor', 'supervisor'), ('grouphead', 'grouphead'), ('people', 'people')], max_length=50, unique=True),
        ),
    ]
