# Generated by Django 6.0.6 on 2026-06-23 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='details',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
    ]
